ASSUME CS:CODE,DS:DATA
CODE SEGMENT
MOV AX,DATA     ;MOVE CONTENTS OF DATA INTO AX
MOV DS,AX       ;MOV CONTENTS OF AX INTO DS
MOV AX,0000H    ;CLEAR/INITIALIZE AX
MOV SI,OFFSET NUMBERS   ;MOVE ADRESS OF NUMBERS INTO SI
MOV AX,[SI]     ;MOVE ele1 INTO AX 
MOV BX,[SI+02]  ;MOVE ele2 INTO BX
MUL BX          ;MULTIPLY CONTENTS OF AX WITH BX
;1234h X 5678h = 06260060h
;DX = 0626h
;AX = 0060h
;RESULT = DXAX => 06260060
HLT             
CODE ENDS
DATA SEGMENT
NUMBERS DW 1234H,5678H
DATA ENDS
END