JNB PSW.7 ABC 		;JUMP IF NOT  CARRY BIT OF PSW TO ABC
SETB PSW.4			;SET PSW.4 BIT
CLR PSW.3				;CLEAR PSW.3 BIT
SJUMP LAST			;SHORT JUMP LAST
ABC:SETB PSW.3	;SET BIT PSW.3
		CLR PSW.4		;CLEAR PSW.4
LAST:NOP				;NO OPERATION
END							;END PROGRAM	
	