ORG 00H     		; SET ADRESS AS 00H
LJMP MAIN   	; LONG JUMP TO MAIN
ORG 0003H   	; SET ADDRESS AS 0003H
MOV A, #15H 	; MOVE 15h INTO A
RETI        		; RETURN FROM INTERRUPT (EXIT FROM INTERRUPT)
ORG 0080H   	;SET ADDRESS AS 0080H
MAIN : MOV IE,#81H  	; SET IE REGISTER VALUE TO #81H
MOV A, #45H         		;MOVE 45H INTO A
SWAPPING: SWAP A   ; SWAPS VALUES TO 45H <-> 54H
SJMP SWAPPING     	; SHORT JUMP SWAPPING 
END                 			; END OF PROGRAM