ORG 00H					;SET ORGIN ADDRESS 00H
MOV TMOD, #01H	        ;SET TMOD VALUE TO 01H
MOV TH0,#0FFH		    ;SET TIMER1 HIGHER VALUE #FFH SETS TF0 HIGH WHEN TIMER REACHES THIS VALUE
MOV TL0,#0FAH		    ;SET TIMER0 LOWER VALUE TO #FAH TIMER STARTS COUNTING AT THIS VALUE
SETB TR0				;SET BIT TR0 (SET TIMER0 TO RUN)
AGAIN:JNB TF0,AGAIN	    ;STAY IN AGAIN UNTIL TIMER OVERFLOW
CLR TR0					;CLEAR TIMER0 RUN BIT TO 0
CLR TF0					;CLEAR TIMER0 OVERFLOW TO0
END						;END PROGRAM