ASSUME CS:CODE,DS:DATA
CODE SEGMENT
MOV AX,DATA     ;MOVE CONTENTS OF DATA INTO AX
MOV DS,AX       ;MOV CONTENTS OF AX INTO DS
MOV AX,0000H    ;CLEAR/INITIALIZE AX
MOV SI,OFFSET NUMBERS   ;MOVE ADRESS OF NUMBERS INTO SI
MOV AX,[SI]     ;MOVE ele1 INTO AX 
MOV BX,[SI+02]  ;MOVE ele2 INTO BX
DIV BX          ;DIVIDE CONTENTS OF AX WITH BX
;1234h / 5678h = 0h REMAINDER = 1234H
;DX = 1234H
;AX = 0H
;RESULT = 0 
;REMAINDER = 1234H
HLT             
CODE ENDS
DATA SEGMENT
NUMBERS DW 1234H,5678H
DATA ENDS
END