ASSUME CS:CODE,DS:DATA
CODE SEGMENT
MOV AX,0000H    ;CLEAR AX
MOV AX,DATA     ;MOVE CONTENTS OF DATA INTO AX
MOV DS,AX       ;MOV CONTENTS OF AX INTO DS
MOV AX,0000H    ;CLEAR/INITIALIZE AX
MOV SI,OFFSET NUMBERS   ;MOVE ADRESS OF NUMBERS INTO SI
MOV AX,[SI]     ;MOVE ele1 INTO AX
MOV BX,[SI+02]  ;MOVE ele2 INTO BX
SUB AX,BX       ;SUBTRACT CONTENTS OF BX FROM AX
MOV CX,AX       ;MOVE CONTENTS OF AX INTO CX (THE RESULT)
HLT             ;STOP CODE
CODE ENDS
DATA SEGMENT
NUMBERS DW 0009H,0006H  ;DECLARE ARRAY NUMBERS 
RES DW ?                ;DECLARE EMPTY DATA-WORD
DATA ENDS
END                     ;PROGRAM ENDS